plugins {
    id 'net.fabricmc.fabric-loom-remap' version '1.17.5'
    id 'com.gradleup.shadow' version '8.3.6'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven {
        name = "Fabric"
        url = "https://maven.fabricmc.net/"
    }
    maven { url = "https://jitpack.io/" }
    maven { url = "https://api.modrinth.com/maven" }
}

configurations {
    shadowImpl
    implementation.extendsFrom shadowImpl
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    implementation 'org.jetbrains:annotations:24.0.0'

    shadowImpl "io.github.spair:imgui-java-binding:${project.imguiVersion}"
    shadowImpl "io.github.spair:imgui-java-lwjgl3:${project.imguiVersion}"
    shadowImpl "io.github.spair:imgui-java-natives-windows-ft:${project.imguiVersion}"
    shadowImpl "io.github.spair:imgui-java-natives-linux-ft:${project.imguiVersion}"
    shadowImpl "io.github.spair:imgui-java-natives-macos-ft:${project.imguiVersion}"

    testImplementation "org.junit.jupiter:junit-jupiter-api:5.10.2"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.10.2"
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
               "minecraft_version": project.minecraft_version,
               "loader_version": project.loader_version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

shadowJar {
    configurations = [project.configurations.shadowImpl]
    archiveClassifier.set('shadow')

    dependencies {
        exclude(dependency('org.lwjgl:lwjgl'))
        exclude(dependency('org.lwjgl:lwjgl-glfw'))
        exclude(dependency('org.lwjgl:lwjgl-opengl'))
    }
}

remapJar {
    dependsOn shadowJar
    inputFile.set(shadowJar.archiveFile)
}
